export type Direction = "across" | "down";

export interface WordData {
  word: string;
  hint: string;
  direction: Direction;
  row: number;
  col: number;
}

export interface LevelData {
  id: number;
  title: string;
  theme: string;
  gridSize: number;
  words: WordData[];
}

export const LEVELS: LevelData[] = [
  {
    id: 1,
    title: "Level 1",
    theme: "Jesus' Early Life",
    gridSize: 10,
    words: [
      {
        word: "BETHLEHEM",
        hint: "The town where Jesus was born.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "NAZARETH",
        hint: "The town where Jesus grew up.",
        direction: "across",
        row: 1,
        col: 0,
      },
      {
        word: "JOSEPH",
        hint: "Jesus' earthly father.",
        direction: "down",
        row: 0,
        col: 9,
      },
      {
        word: "MARY",
        hint: "The mother of Jesus.",
        direction: "down",
        row: 0,
        col: 8,
      },
      {
        word: "EGYPT",
        hint: "Where the holy family fled to escape Herod.",
        direction: "down",
        row: 1,
        col: 5,
      },
      {
        word: "HEROD",
        hint: "The king who feared Jesus' birth and killed young boys.",
        direction: "down",
        row: 1,
        col: 7,
      },
    ],
  },
  {
    id: 2,
    title: "Level 2",
    theme: "Old Testament Journey",
    gridSize: 8,
    words: [
      {
        word: "EDEN",
        hint: "The garden where Adam and Eve lived.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "SINAI",
        hint: "The mountain where Moses received the Ten Commandments.",
        direction: "across",
        row: 2,
        col: 1,
      },
      {
        word: "CANAAN",
        hint: "The promised land God gave to the Israelites.",
        direction: "down",
        row: 1,
        col: 4,
      },
      {
        word: "EGYPT",
        hint: "The land where the Israelites were enslaved for 400 years.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "JORDAN",
        hint: "The river the Israelites crossed to enter the promised land.",
        direction: "across",
        row: 5,
        col: 0,
      },
      {
        word: "BABEL",
        hint: "The city where God confused the languages of the people.",
        direction: "across",
        row: 4,
        col: 3,
      },
    ],
  },
  {
    id: 3,
    title: "Level 3",
    theme: "Paul's Missions",
    gridSize: 9,
    words: [
      {
        word: "ANTIOCH",
        hint: "The city where believers were first called Christians.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "EPHESUS",
        hint: "The city where Paul stayed for three years and taught daily.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "PHILIPPI",
        hint: "The city where Paul and Silas were imprisoned and freed.",
        direction: "across",
        row: 1,
        col: 1,
      },
      {
        word: "ATHENS",
        hint: 'The city where Paul preached about the "Unknown God."',
        direction: "across",
        row: 4,
        col: 2,
      },
      {
        word: "CORINTH",
        hint: "The city where Paul wrote letters to the early church.",
        direction: "across",
        row: 2,
        col: 1,
      },
      {
        word: "ROME",
        hint: "The city that Paul traveled to as a prisoner and taught about Christ.",
        direction: "across",
        row: 3,
        col: 4,
      },
    ],
  },
  {
    id: 4,
    title: "Level 4",
    theme: "Prophetic Cities",
    gridSize: 9,
    words: [
      {
        word: "NINEVEH",
        hint: "The great city where Jonah preached repentance.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "BABYLON",
        hint: "The empire that conquered Judah and took the people into exile.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "TYRE",
        hint: "A wealthy coastal city often cursed by the prophets.",
        direction: "down",
        row: 0,
        col: 8,
      },
      {
        word: "SODOM",
        hint: "A city destroyed for its wickedness by fire and brimstone.",
        direction: "across",
        row: 5,
        col: 4,
      },
      {
        word: "SAMARIA",
        hint: "The capital of the northern kingdom of Israel.",
        direction: "across",
        row: 1,
        col: 1,
      },
    ],
  },
  {
    id: 5,
    title: "Level 5",
    theme: "Regions & Lands",
    gridSize: 8,
    words: [
      {
        word: "JUDEA",
        hint: "The region where Jerusalem is located.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "SHARON",
        hint: "A fertile plain in Israel known for its beauty and flowers.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "GAZA",
        hint: "A coastal city associated with Samson.",
        direction: "across",
        row: 2,
        col: 4,
      },
      {
        word: "GALILEE",
        hint: "The region where Jesus spent most of His ministry.",
        direction: "down",
        row: 1,
        col: 7,
      },
      {
        word: "MOAB",
        hint: "The land east of the Dead Sea, home of Ruth.",
        direction: "across",
        row: 1,
        col: 0,
      },
      {
        word: "PATMOS",
        hint: "The island where John received the Book of Revelation.",
        direction: "across",
        row: 4,
        col: 1,
      },
    ],
  },
  {
    id: 6,
    title: "Level 6",
    theme: "Patriarchs",
    gridSize: 9,
    words: [
      {
        word: "ADAM",
        hint: "The first man created by God.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "ABEL",
        hint: "The first person murdered in the Bible.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "NOAH",
        hint: "The man who built the ark and survived the great flood.",
        direction: "across",
        row: 0,
        col: 4,
      },
      {
        word: "ABRAHAM",
        hint: "The father of faith who was called by God and promised many descendants.",
        direction: "down",
        row: 0,
        col: 2,
      },
      {
        word: "ISAAC",
        hint: "The promised son of Abraham and Sarah.",
        direction: "across",
        row: 5,
        col: 0,
      },
      {
        word: "JACOB",
        hint: "The patriarch who wrestled with God and was renamed Israel.",
        direction: "down",
        row: 4,
        col: 3,
      },
    ],
  },
  {
    id: 7,
    title: "Level 7",
    theme: "Leaders of Israel",
    gridSize: 8,
    words: [
      {
        word: "MOSES",
        hint: "Led the Israelites out of Egypt through the Red Sea.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "JOSHUA",
        hint: "Led Israel into the Promised Land after Moses.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "GIDEON",
        hint: "The judge who defeated the Midianites with 300 men.",
        direction: "across",
        row: 1,
        col: 1,
      },
      {
        word: "SAMSON",
        hint: "The strongest judge whose power came from his uncut hair.",
        direction: "across",
        row: 2,
        col: 2,
      },
      {
        word: "DEBORAH",
        hint: "The only female judge who led Israel to victory.",
        direction: "across",
        row: 5,
        col: 0,
      },
    ],
  },
  {
    id: 8,
    title: "Level 8",
    theme: "Kings",
    gridSize: 9,
    words: [
      {
        word: "SAUL",
        hint: "The first king of Israel, chosen by God.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "DAVID",
        hint: "The shepherd boy who became king and defeated Goliath.",
        direction: "across",
        row: 3,
        col: 1,
      },
      {
        word: "SOLOMON",
        hint: "The wisest king who built the first temple in Jerusalem.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "REHOBOAM",
        hint: "Solomon's son whose harsh rule split the kingdom.",
        direction: "across",
        row: 1,
        col: 1,
      },
      {
        word: "JOSIAH",
        hint: "The young king who found the lost Book of the Law and reformed Israel.",
        direction: "down",
        row: 0,
        col: 4,
      },
    ],
  },
  {
    id: 9,
    title: "Level 9",
    theme: "Prophets",
    gridSize: 9,
    words: [
      {
        word: "ISAIAH",
        hint: "The prophet who foretold the coming of the Messiah in detail.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "JEREMIAH",
        hint: "The weeping prophet who warned Judah of coming destruction.",
        direction: "across",
        row: 0,
        col: 1,
      },
      {
        word: "DANIEL",
        hint: "The prophet who survived the lion's den by faith.",
        direction: "down",
        row: 1,
        col: 1,
      },
      {
        word: "EZEKIEL",
        hint: "The prophet who saw visions of dry bones coming to life.",
        direction: "down",
        row: 0,
        col: 2,
      },
      {
        word: "HOSEA",
        hint: "The prophet whose marriage illustrated God's love for unfaithful Israel.",
        direction: "down",
        row: 0,
        col: 8,
      },
    ],
  },
  {
    id: 10,
    title: "Level 10",
    theme: "New Testament",
    gridSize: 8,
    words: [
      {
        word: "PETER",
        hint: "The disciple who walked on water and became a leader of the early church.",
        direction: "across",
        row: 0,
        col: 1,
      },
      {
        word: "PAUL",
        hint: "The apostle who spread the gospel to the Gentiles and wrote many epistles.",
        direction: "down",
        row: 0,
        col: 1,
      },
      {
        word: "JOHN",
        hint: "The beloved disciple who wrote a Gospel, three letters, and Revelation.",
        direction: "across",
        row: 4,
        col: 4,
      },
      {
        word: "MARY",
        hint: 'The mother of Jesus who said "Let it be done according to your word."',
        direction: "across",
        row: 1,
        col: 0,
      },
      {
        word: "STEPHEN",
        hint: "The first Christian martyr, stoned for his faith.",
        direction: "down",
        row: 0,
        col: 6,
      },
    ],
  },
  {
    id: 11,
    title: "Level 11",
    theme: "Exodus Events",
    gridSize: 8,
    words: [
      {
        word: "PLAGUES",
        hint: "The ten devastating judgments sent upon Egypt before the Exodus.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "PASSOVER",
        hint: "The sacred feast commemorating Israel's deliverance from slavery in Egypt.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "SINAI",
        hint: "The mountain where God gave Moses the Ten Commandments.",
        direction: "down",
        row: 0,
        col: 6,
      },
      {
        word: "MANNA",
        hint: "The miraculous bread from heaven that fed the Israelites in the wilderness.",
        direction: "across",
        row: 2,
        col: 3,
      },
      {
        word: "REDSEA",
        hint: "The sea that parted so the Israelites could escape from Egypt.",
        direction: "across",
        row: 7,
        col: 0,
      },
    ],
  },
  {
    id: 12,
    title: "Level 12",
    theme: "Jesus' Miracles",
    gridSize: 10,
    words: [
      {
        word: "LAZARUS",
        hint: "The man whom Jesus raised from the dead.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "BLIND",
        hint: "Refers to those whom Jesus healed of their sight.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "LOAVES",
        hint: "The bread multiplied by Jesus to feed the five thousand.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "WINE",
        hint: "The drink Jesus miraculously created at the wedding in Cana.",
        direction: "across",
        row: 2,
        col: 6,
      },
      {
        word: "STORM",
        hint: "The violent storm that Jesus calmed with His command.",
        direction: "across",
        row: 5,
        col: 0,
      },
    ],
  },
  {
    id: 13,
    title: "Level 13",
    theme: "Parables of Jesus",
    gridSize: 9,
    words: [
      {
        word: "SOWER",
        hint: "The farmer in Jesus' parable who scattered seeds on different soils.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "TALENTS",
        hint: "The money entrusted to servants in a parable about faithfulness.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "PRODIGAL",
        hint: "The wayward son who returned home and was welcomed by his father.",
        direction: "across",
        row: 7,
        col: 0,
      },
      {
        word: "MUSTARD",
        hint: "The tiny seed Jesus compared to the kingdom of heaven.",
        direction: "down",
        row: 2,
        col: 1,
      },
      {
        word: "PEARL",
        hint: "The precious gem a merchant sold everything to buy in Jesus' parable.",
        direction: "across",
        row: 3,
        col: 4,
      },
    ],
  },
  {
    id: 14,
    title: "Level 14",
    theme: "Women of the Bible",
    gridSize: 9,
    words: [
      {
        word: "RUTH",
        hint: "The Moabite woman who remained loyal to her mother-in-law Naomi.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "ESTHER",
        hint: "The queen who risked her life to save her people from destruction.",
        direction: "down",
        row: 0,
        col: 4,
      },
      {
        word: "SARAH",
        hint: "Abraham's wife who gave birth to Isaac in her old age.",
        direction: "across",
        row: 1,
        col: 4,
      },
      {
        word: "RAHAB",
        hint: "The woman of Jericho who hid the Israelite spies.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "HANNAH",
        hint: "The faithful mother who dedicated her son Samuel to God.",
        direction: "down",
        row: 0,
        col: 3,
      },
      {
        word: "MIRIAM",
        hint: "Moses' sister who led women in song after crossing the Red Sea.",
        direction: "down",
        row: 1,
        col: 1,
      },
    ],
  },
  {
    id: 15,
    title: "Level 15",
    theme: "Armor of God",
    gridSize: 9,
    words: [
      {
        word: "TRUTH",
        hint: "The belt of the Christian's spiritual armor (Ephesians 6).",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "SHIELD",
        hint: "The piece of armor that extinguishes the flaming arrows of the evil one.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "HELMET",
        hint: "The headpiece representing salvation in the armor of God.",
        direction: "across",
        row: 4,
        col: 3,
      },
      {
        word: "SWORD",
        hint: "The weapon of the Spirit, which is the Word of God.",
        direction: "across",
        row: 5,
        col: 1,
      },
      {
        word: "FAITH",
        hint: "The shield that protects believers from spiritual attacks.",
        direction: "across",
        row: 2,
        col: 3,
      },
      {
        word: "GOSPEL",
        hint: "The good news of peace that prepares the believer's feet.",
        direction: "across",
        row: 3,
        col: 1,
      },
    ],
  },
  {
    id: 16,
    title: "Level 16",
    theme: "Creation",
    gridSize: 8,
    words: [
      {
        word: "LIGHT",
        hint: "The first thing God created on day one of creation.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "WATERS",
        hint: "God separated these above and below the expanse on day two.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "STARS",
        hint: "The lights God placed in the sky on the fourth day.",
        direction: "across",
        row: 1,
        col: 3,
      },
      {
        word: "ANIMALS",
        hint: "The living creatures God made on the fifth and sixth days.",
        direction: "down",
        row: 1,
        col: 0,
      },
      {
        word: "PLANTS",
        hint: "The vegetation God caused to grow from the earth on day three.",
        direction: "across",
        row: 2,
        col: 1,
      },
      {
        word: "SABBATH",
        hint: "The day God rested after completing creation.",
        direction: "across",
        row: 7,
        col: 0,
      },
    ],
  },
  {
    id: 17,
    title: "Level 17",
    theme: "Fruits of the Spirit",
    gridSize: 10,
    words: [
      {
        word: "LOVE",
        hint: "The greatest fruit of the Spirit and the greatest commandment.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "JOY",
        hint: "A deep gladness that comes from the Holy Spirit, not circumstances.",
        direction: "down",
        row: 0,
        col: 4,
      },
      {
        word: "PEACE",
        hint: "The fruit of the Spirit that guards the heart and mind.",
        direction: "across",
        row: 0,
        col: 5,
      },
      {
        word: "PATIENCE",
        hint: "The fruit of enduring without complaint, also called longsuffering.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "KINDNESS",
        hint: "The fruit of the Spirit shown through generous and caring actions.",
        direction: "across",
        row: 5,
        col: 1,
      },
      {
        word: "GOODNESS",
        hint: "The fruit of moral excellence and righteous living.",
        direction: "across",
        row: 4,
        col: 0,
      },
    ],
  },
  {
    id: 18,
    title: "Level 18",
    theme: "Twelve Disciples",
    gridSize: 9,
    words: [
      {
        word: "ANDREW",
        hint: "Simon Peter's brother who first followed Jesus.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "THOMAS",
        hint: "The disciple who doubted Jesus' resurrection until he saw Him.",
        direction: "down",
        row: 0,
        col: 6,
      },
      {
        word: "JAMES",
        hint: "The son of Zebedee and brother of John, one of Jesus' inner circle.",
        direction: "across",
        row: 3,
        col: 4,
      },
      {
        word: "MATTHEW",
        hint: "The tax collector who left everything to follow Jesus.",
        direction: "down",
        row: 2,
        col: 5,
      },
      {
        word: "PHILIP",
        hint: "The disciple from Bethsaida who brought Nathanael to Jesus.",
        direction: "across",
        row: 1,
        col: 0,
      },
      {
        word: "JUDAS",
        hint: "The disciple who betrayed Jesus for thirty pieces of silver.",
        direction: "down",
        row: 3,
        col: 4,
      },
    ],
  },
  {
    id: 19,
    title: "Level 19",
    theme: "Animals in the Bible",
    gridSize: 9,
    words: [
      {
        word: "SERPENT",
        hint: "The crafty creature that tempted Eve in the Garden of Eden.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "DOVE",
        hint: "The bird that returned to Noah with an olive branch.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "LAMB",
        hint: "The sacrificial animal that symbolizes Jesus, the Lamb of God.",
        direction: "across",
        row: 1,
        col: 0,
      },
      {
        word: "LION",
        hint: "The beast Daniel was thrown among, and a title for Jesus from Judah.",
        direction: "down",
        row: 1,
        col: 0,
      },
      {
        word: "WHALE",
        hint: "The great sea creature that swallowed Jonah for three days.",
        direction: "across",
        row: 3,
        col: 3,
      },
      {
        word: "DONKEY",
        hint: "The animal Jesus rode into Jerusalem on Palm Sunday.",
        direction: "across",
        row: 2,
        col: 1,
      },
    ],
  },
  {
    id: 20,
    title: "Level 20",
    theme: "Worship & Praise",
    gridSize: 9,
    words: [
      {
        word: "PSALM",
        hint: "A sacred song or hymn found in the Old Testament book of songs.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "PRAISE",
        hint: "The act of glorifying God through words and song.",
        direction: "down",
        row: 0,
        col: 0,
      },
      {
        word: "TEMPLE",
        hint: "The holy house of worship built by Solomon in Jerusalem.",
        direction: "across",
        row: 1,
        col: 1,
      },
      {
        word: "ALTAR",
        hint: "The raised structure where sacrifices and offerings were made to God.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "TITHE",
        hint: "The tenth portion given to God as an offering.",
        direction: "across",
        row: 2,
        col: 3,
      },
      {
        word: "HYMN",
        hint: "A song of praise Jesus and His disciples sang at the Last Supper.",
        direction: "down",
        row: 2,
        col: 6,
      },
    ],
  },
  {
    id: 21,
    title: "Level 21",
    theme: "The Tabernacle",
    gridSize: 10,
    words: [
      {
        word: "CURTAIN",
        hint: "The fabric barrier separating the Holy Place from the Most Holy Place.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "ARK",
        hint: "The gold-covered chest that held the Ten Commandments.",
        direction: "down",
        row: 0,
        col: 4,
      },
      {
        word: "INCENSE",
        hint: "The fragrant offering burned on the golden altar before God.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "LAMP",
        hint: "The golden stand that provided light inside the Holy Place.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "TABLE",
        hint: "The surface where the showbread was placed before the Lord.",
        direction: "across",
        row: 3,
        col: 1,
      },
      {
        word: "VEIL",
        hint: "The inner covering that was torn in two when Jesus died on the cross.",
        direction: "across",
        row: 6,
        col: 4,
      },
    ],
  },
  {
    id: 22,
    title: "Level 22",
    theme: "Ten Commandments",
    gridSize: 9,
    words: [
      {
        word: "HONOR",
        hint: "The commandment to respect your father and mother.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "STEAL",
        hint: "What the eighth commandment forbids doing.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "MURDER",
        hint: "The act forbidden by the sixth commandment.",
        direction: "across",
        row: 2,
        col: 1,
      },
      {
        word: "COVET",
        hint: "To wrongly desire what belongs to your neighbor, forbidden by God.",
        direction: "across",
        row: 1,
        col: 1,
      },
      {
        word: "IDOLS",
        hint: "Graven images the second commandment forbids worshiping.",
        direction: "across",
        row: 4,
        col: 2,
      },
      {
        word: "SABBATH",
        hint: "The holy day the fourth commandment tells us to remember and keep.",
        direction: "across",
        row: 3,
        col: 1,
      },
    ],
  },
  {
    id: 23,
    title: "Level 23",
    theme: "Prayers in the Bible",
    gridSize: 9,
    words: [
      {
        word: "AMEN",
        hint: 'The word meaning "so be it" used to close a prayer.',
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "FASTING",
        hint: "The practice of going without food to draw closer to God in prayer.",
        direction: "down",
        row: 0,
        col: 4,
      },
      {
        word: "FORGIVE",
        hint: "What Jesus taught us to ask God for in the Lord's Prayer.",
        direction: "across",
        row: 6,
        col: 1,
      },
      {
        word: "KNEEL",
        hint: "The posture Daniel took three times a day while praying to God.",
        direction: "down",
        row: 4,
        col: 7,
      },
      {
        word: "SEEK",
        hint: '"___ and you will find" — Jesus\' promise about prayer.',
        direction: "across",
        row: 2,
        col: 4,
      },
      {
        word: "THANKS",
        hint: "What Paul said should accompany every prayer (Philippians 4:6).",
        direction: "across",
        row: 1,
        col: 2,
      },
    ],
  },
  {
    id: 24,
    title: "Level 24",
    theme: "Heaven & Angels",
    gridSize: 9,
    words: [
      {
        word: "GABRIEL",
        hint: "The angel who announced the birth of Jesus to Mary.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "MICHAEL",
        hint: "The archangel who fights against the dragon in Revelation.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "THRONE",
        hint: "The seat of God's authority and glory in heaven.",
        direction: "across",
        row: 5,
        col: 2,
      },
      {
        word: "SERAPH",
        hint: 'The six-winged angel who cried "Holy, holy, holy" in Isaiah\'s vision.',
        direction: "down",
        row: 3,
        col: 4,
      },
      {
        word: "CHERUB",
        hint: "The angelic being that guarded the entrance to the Garden of Eden.",
        direction: "across",
        row: 8,
        col: 3,
      },
      {
        word: "GLORY",
        hint: "The radiant splendor that fills God's heavenly dwelling.",
        direction: "down",
        row: 0,
        col: 0,
      },
    ],
  },
  {
    id: 25,
    title: "Level 25",
    theme: "The Promised Land",
    gridSize: 10,
    words: [
      {
        word: "JERICHO",
        hint: "The walled city whose walls fell after Israel marched around it.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "HEBRON",
        hint: "The city where Abraham lived and where David was first anointed king.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "SHILOH",
        hint: "The city where the Tabernacle rested after the conquest of Canaan.",
        direction: "across",
        row: 4,
        col: 1,
      },
      {
        word: "GILGAL",
        hint: "The first camp of the Israelites after crossing the Jordan River.",
        direction: "down",
        row: 3,
        col: 3,
      },
      {
        word: "KADESH",
        hint: "The place where the twelve spies were sent out to scout the land.",
        direction: "across",
        row: 1,
        col: 2,
      },
      {
        word: "CALEB",
        hint: "The faithful spy who believed God could give Israel the Promised Land.",
        direction: "down",
        row: 2,
        col: 4,
      },
    ],
  },
  {
    id: 26,
    title: "Level 26",
    theme: "Psalms & Wisdom",
    gridSize: 9,
    words: [
      {
        word: "WISDOM",
        hint: "The virtue Proverbs says is more precious than rubies.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "PROVERB",
        hint: "A short wise saying, many of which were written by Solomon.",
        direction: "down",
        row: 0,
        col: 6,
      },
      {
        word: "SELAH",
        hint: "A mysterious word found throughout the Psalms, likely a musical pause.",
        direction: "down",
        row: 0,
        col: 2,
      },
      {
        word: "REFUGE",
        hint: "What the Psalmist calls God — a safe shelter in times of trouble.",
        direction: "down",
        row: 0,
        col: 7,
      },
      {
        word: "VANITY",
        hint: '"___ of vanities" — the Teacher\'s refrain in Ecclesiastes.',
        direction: "across",
        row: 5,
        col: 0,
      },
      {
        word: "FEAR",
        hint: "The beginning of wisdom, according to Proverbs 9:10.",
        direction: "across",
        row: 1,
        col: 3,
      },
    ],
  },
  {
    id: 27,
    title: "Level 27",
    theme: "Battles & Victories",
    gridSize: 10,
    words: [
      {
        word: "GOLIATH",
        hint: "The giant Philistine warrior defeated by a young shepherd boy.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "ARMOR",
        hint: "The heavy gear Saul offered David, which David refused to wear.",
        direction: "down",
        row: 0,
        col: 4,
      },
      {
        word: "MIDIAN",
        hint: "The enemy nation Gideon defeated with only three hundred men.",
        direction: "across",
        row: 2,
        col: 4,
      },
      {
        word: "AMALEK",
        hint: "The enemy defeated when Moses held up his hands during battle.",
        direction: "down",
        row: 2,
        col: 8,
      },
      {
        word: "TRUMPET",
        hint: "The instrument blown before the walls of Jericho fell down.",
        direction: "across",
        row: 1,
        col: 3,
      },
      {
        word: "SPEAR",
        hint: "The weapon Saul hurled at David in jealous anger.",
        direction: "across",
        row: 4,
        col: 0,
      },
    ],
  },
  {
    id: 28,
    title: "Level 28",
    theme: "Covenants & Promises",
    gridSize: 9,
    words: [
      {
        word: "RAINBOW",
        hint: "The sign God placed in the sky as a promise never to flood the earth again.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "BLOOD",
        hint: "The element that sealed the new covenant through Jesus' sacrifice.",
        direction: "down",
        row: 0,
        col: 4,
      },
      {
        word: "COVENANT",
        hint: "A sacred binding agreement between God and His people.",
        direction: "across",
        row: 5,
        col: 0,
      },
      {
        word: "PROMISE",
        hint: "What God made to Abraham about descendants as numerous as the stars.",
        direction: "across",
        row: 2,
        col: 2,
      },
      {
        word: "SIGN",
        hint: "Circumcision served as this for God's covenant with Abraham.",
        direction: "down",
        row: 1,
        col: 6,
      },
      {
        word: "OATH",
        hint: "A solemn vow God swore to confirm His promises.",
        direction: "down",
        row: 5,
        col: 1,
      },
    ],
  },
  {
    id: 29,
    title: "Level 29",
    theme: "Revelation & End Times",
    gridSize: 10,
    words: [
      {
        word: "DRAGON",
        hint: "The great beast in Revelation that represents Satan.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "SEAL",
        hint: "One of seven broken open by the Lamb, unleashing judgment on the earth.",
        direction: "across",
        row: 0,
        col: 6,
      },
      {
        word: "TRUMPET",
        hint: "One of seven sounded by angels, bringing plagues in Revelation.",
        direction: "across",
        row: 6,
        col: 0,
      },
      {
        word: "BEAST",
        hint: "The creature rising from the sea with seven heads and ten horns.",
        direction: "down",
        row: 2,
        col: 6,
      },
      {
        word: "HEAVEN",
        hint: "The new dwelling place God will create for His people at the end of time.",
        direction: "across",
        row: 3,
        col: 2,
      },
      {
        word: "ALPHA",
        hint: "Jesus calls Himself this and Omega — the beginning and the end.",
        direction: "down",
        row: 0,
        col: 2,
      },
    ],
  },
  {
    id: 30,
    title: "Level 30",
    theme: "Names of God",
    gridSize: 10,
    words: [
      {
        word: "JEHOVAH",
        hint: "The personal covenant name of God revealed to Moses at the burning bush.",
        direction: "across",
        row: 0,
        col: 0,
      },
      {
        word: "ALMIGHTY",
        hint: "El Shaddai — God's name meaning all-powerful and supreme.",
        direction: "down",
        row: 0,
        col: 5,
      },
      {
        word: "ELOHIM",
        hint: "The Hebrew name for God used in the very first verse of Genesis.",
        direction: "across",
        row: 1,
        col: 4,
      },
      {
        word: "ADONAI",
        hint: "The Hebrew name meaning Lord or Master, used in place of God's name.",
        direction: "across",
        row: 3,
        col: 0,
      },
      {
        word: "ABBA",
        hint: "The intimate Aramaic word for Father used by Jesus in prayer.",
        direction: "down",
        row: 3,
        col: 0,
      },
      {
        word: "SHALOM",
        hint: 'Jehovah ___ — the name meaning "The Lord is Peace."',
        direction: "across",
        row: 5,
        col: 4,
      },
    ],
  },
];
